### ISSUE TITLE
Windows 10: CTRL+C does not kill server

### ISSUE THREAD

**Issue by pllim** [QuantStack/voila#100]
I started `voila some_notebook.ipynb`, ran into #98 and unable to kill it with CTRL+C. The ugly workaround is to reboot the machine. I am using it via Git Bash shell.

**Comment by maartenbreddels** [comment]
Thanks for reporting, I think rebooting is not needed. Find the Python process in the task manager so you can kill the process.

**Comment by pllim** [comment]
I did try to find it in Task Manager but I can't tell what is what and didn't want to risk a BSOD. I did find one instance of `voila.exe` and killed that one but it didn't help, as afterwards I still got an error from Windows about a process is already running on the desired port number, hence #99.

**Comment by pllim** [comment]
UPDATE: I finally found a "Python" job in Task Manager and killing that one seems to have freed up the port.

**Comment by SylvainCorlay** [comment]
Thanks @pllim ! closing the issue.

**Comment by pllim** [comment]
Wait, I found a workaround, but it is not painless, as I still need lost my terminal and manually kill the job in Task Manager. Would be nice if CTRL+C works as expected ™️ .

FWIW, when running it via [this script](https://github.com/spacetelescope/dat_pyinthesky/blob/master/jupyter_platform/astrowidgets_viewer_win), CTRL+C works, but not when running `voila` directly from terminal as your README suggests.

**Comment by pllim** [comment]
(I don't know why I cannot re-open an issue that I created to begin with. Please re-open this issue.)

**Comment by vidartf** [comment]
PS: While I think Ctrl + C would be nice, on Windows you can also try the more assertive Ctrl + Pause/Break. That sends a signal that the user code cannot prevent.

**Comment by pllim** [comment]
@vidartf , thanks for the tip, but what is a "pause/break" button? I am using a laptop and there does not appear to be one that says "pause" or "break".

**Comment by vidartf** [comment]
https://en.wikipedia.org/wiki/Break_key#Keyboards_without_Break_key

**Comment by pllim** [comment]
Thanks, but can't say I am a fan of that laptop substitute.
