### ISSUE TITLE
Bug: Race condition on widget render

### ISSUE THREAD

**Issue by timkpaine** [QuantStack/voila#104]
Not sure this is fixable, but heres what i'm seeing:

if `plotlywidget.js` is present locally, the chart renders no problem.

if not, then the graph is attempted to be rendered while the js is being fetched from unpkg, and the chart is never displayed.

Presumably this affects other libraries as well (though not qgrid it seems).

**Comment by SylvainCorlay** [comment]
This looks like an issue with plotly.

cc @jonmmease I presume that the embedding of the plotly interactive widget is not a typical scenario since plotly has other means to be embedded into web contexts.

**Comment by jonmmease** [comment]
@timkpaine I assume you're displaying the plotly figure as a `FigureWidget`?  I haven't tested out `FigureWidget` in voila yet, but they have worked alright in the past with nbviewer which is also pulling the plotlywidget package from unpkg.

Also, what do you mean by "if plotlywidget.js is present locally" in the context of Voila?

**Comment by timkpaine** [comment]
@jonmmease locally here meaning that there is a `/usr/local/share/jupyter/nbextensions/plotlywidget/index.js`

**Comment by DougRzz** [comment]
@jonmmease Plotly works very nicely in my Voila app. At least the contour plot does and it looks great :). Bqplot and Plotly working together in perfect harmony.

**Comment by DougRzz** [comment]
@timkpaine  Not sure if this would help your issue or not but the code that I used to create the Plotly widget is shown below.   Screencast of Plotly contour plot with a Bqplot heatmap,  as part of a Voila app, is shown at the bottom.

```python
import plotly.graph_objs as go

        dataContour =[go.Contour(
                contours=dict(
                    coloring ='heatmap',
                    #coloring ='contour',
                    showlabels = True,
                    labelfont = dict(
                        family = 'Raleway',
                        size = 12,
                        color = 'Black',
                        )))
                        ]

plotlyFig = go.Figure(data=dataContour)
plotlyFig['layout'].update(height=800, 
                            width=800, 
                            title='',
                            xaxis=dict(
                                title='x Axis',
                                titlefont=dict(
                                    family='Arial',
                                    size=18,
                                    color='#7f7f7f'
                                )
                            ),
                            yaxis=dict(
                                title='y Axis',
                                titlefont=dict(
                                    family='Arial',
                                    size=18,
                                    color='#7f7f7f'
                                )
                            )                          
                            )
contourPlotlyWidget = go.FigureWidget(plotlyFig)

# Take data from BQplot heatmap (figHeatMap)
contour = contourPlotlyWidget.data[0]
contour.x = figHeatMap.marks[0].x
contour.y = figHeatMap.marks[0].y
contour.z = figHeatMap.marks[0].color

contourPlotlyWidget.layout.xaxis.title = figHeatMap.axes[0].label
contourPlotlyWidget.layout.yaxis.title = figHeatMap.axes[1].label 

```

![BQplot_plotly](https://user-images.githubusercontent.com/3510318/55749334-93738280-5a38-11e9-80d0-f686a39652e5.gif)

**Comment by timkpaine** [comment]
@DougRzz it works perfectly for me, but only if when i install plotly i maintain the extra assets it brings with it (on my mac, this is `/usr/local/share/jupyter/nbextensions/plotlywidget`). If you delete that folder, then i no longer see plots, even with the unpkg failover

**Comment by timkpaine** [comment]
one of the recent PRs or merges has made this go away, closing
