### ISSUE TITLE
JavaScript output is disabled in JupyterLab

### ISSUE THREAD

**Issue by catethos** [QuantStack/voila#108]
I am trying to do
```
from IPython.display import Javascript
Javascript(<some javascript>)
```
It works in noteboook and lab, but I get this error when using voila, any advise?
```
JavaScript output is disabled in JupyterLab
```

**Comment by SylvainCorlay** [comment]
Now fixed in Master.

**Comment by evanlynch** [comment]
Hi, what was the fix? I'm still seeing this error.

**Comment by SylvainCorlay** [comment]
I think I commented on this issue instead of another one. We indeed disallow arbitrary javascript injection in JupyterLab and this is very unlikely to be supported.

**Comment by evanlynch** [comment]
hmm. I don't think I'm doing that. This is where I am seeing the issue: 

If I create an interact widget it works fine in both Lab and Voila

```
def f(x):
    return x
interact(f, x=10);
```

This will show following in both Lab and Voila: 

![image](https://user-images.githubusercontent.com/32716730/60213324-3f0ac280-9831-11e9-902e-157441a2fdf5.png)

But my actual code doesn't work in Voila (although it does in Lab). Essentially what I am doing here is going through a dictionary of charts, where each hour is the key. It works perfectly fine on Lab: 

```
#making the chart for each hour
charts = {}
hours = range(1,8)
def makeChart(hour):
    resultsData = pd.read_csv('Hour7.csv')
    resultsData = resultsData[resultsData.Hour==hour]
    ch = chartify.Chart(blank_labels=True, x_axis_type='categorical')
    ch.set_title("Associate to Door Assignment")
    ch.plot.bar(
        data_frame=resultsData,
        categorical_columns='Door',
        numeric_column='Volume',
        categorical_order_by='labels',
        categorical_order_ascending=True,
        color_column='Assignment')
        #color_order=[i for i in range(1,int(resultsData.Assignment.max())+1)])
    ch.axes.hide_xaxis()
    ch.set_legend_location(None)
    ch.style.color_palette.reset_palette_order()
    return ch

for hour in hours:
    charts[hour] = makeChart(hour)
def showDoorLevelResults(hour):
    f = charts[hour].show('html')
interact(showDoorLevelResults, hour=widgets.IntSlider(min=1,max=7,step=1,value=1));
```
![image](https://user-images.githubusercontent.com/32716730/60213549-bdfffb00-9831-11e9-9fc3-1f907bfaa026.png)
changes to 
![image](https://user-images.githubusercontent.com/32716730/60213578-cce6ad80-9831-11e9-8b0e-b4fbbeccb2e2.png)


This is what I see in Voila

![image](https://user-images.githubusercontent.com/32716730/60213608-dcfe8d00-9831-11e9-9dea-d4f6758c2ef4.png)

**Comment by SylvainCorlay** [comment]
It appears that chartify is using bokeh which is not supported at the moment cf. #244.

Bokeh does not use the jupyter extension system for its javascript but makes use of the javascript injection (js output). We will need to do some special-casing for bokeh to work in voila.

**Comment by SylvainCorlay** [comment]
Also, thanks for adding more details!
In the mean time, using ipympl (matplotlib), bqplot or plotly should work well in voila. Unfortunately, bokeh is another issue.

**Comment by evanlynch** [comment]
Ok, I'll try swapping out bqplot for chartify. Thanks for the response!

**Comment by evanlynch** [comment]
Actually, Sylvain. I'm using Charitfy in other parts of my project, and it's working fine. They are static (ie not controlled by an interact widget). Is there a reason these work, but using along with a widget it does not? The image below is a chartify object copied from voila

![image](https://user-images.githubusercontent.com/32716730/60276008-c6efdb80-98c8-11e9-9750-db78f1558f8d.png)

**Comment by codebraker** [comment]
> It appears that chartify is using bokeh which is not supported at the moment cf. #244.
> 
> Bokeh does not use the jupyter extension system for its javascript but makes use of the javascript injection (js output). We will need to do some special-casing for bokeh to work in voila.

@SylvainCorlay , is bokeh still an issue for voila? Do we have any fixes here? I was so glad to explore Voila over Streamlit for some customisations in bokeh.... Would really appreciate using Voila

**Comment by martinRenou** [comment]
There is some development currently happening in Bokeh for adding support to Voila. Doesn't it work now? Did you try with latest Bokeh?
