### ISSUE TITLE
Add a CONTRIBUTING.md document

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#113]
It would be helpful if there were a document (or multiple documents) to help people get acquainted with the codebase, understand its layout, etc. I've seen presentations from @SylvainCorlay where he's done a good job of explaining the simplicity of voila's design, which I think is fairly powerful.

As 1.0 nears, it would be good to include this kind of documentation around the project.

**Comment by jtpio** [comment]
Thanks @choldgraf! This was fixed in https://github.com/QuantStack/voila/pull/161.
