### ISSUE TITLE
Support a "localhost:<port>/voila/path/to/notebook.ipynb" endpoint

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#114]
Currently if you give 

`localhost:XXXX/voila/path/to/folder`

then voila opens up that folder in the UI to click on notebooks.

When you click a notebook it takes you to

`/voila/render/notebookname`

However, if you give:

`localhost:XXXX/voila/path/to/folder/notebookname.ipynb`

then you get an error.

As a new user, I was expecting to

1. be able to go directly to `/voila/path/to/folder/notebookname.ipynb` and have it render that notebook
2. be able to go directly to `/voila/render/path/to/folder/notebookname.ipynb` and have it render too. (it doesn't, you need to strip the `.ipynb`.

From my perspective it would be a bit more intuitive if either of these cases would trigger the typical voila build behavior. Then again, maybe this will be improved once the docs are in place, but I thought I'd share my experience in case it helps

**Comment by maartenbreddels** [comment]
I think this makes sense as a notebook producer, but I think end users will not want to see the .ipynb. To them, it should (in my opinion) be a web server hosting apps/pages. 

`/voila` is a common prefix to all paths, so `/voila/tree` should give you the tree view, `/voila/render/path/to/notebook` is analog to the notebook's `/notebooks/path/to/notebook.ipynb`.

Does it make more sense, does it change your opinion, or you still find it unintuitive?

**Comment by choldgraf** [comment]
Well as you say, I don't know that I'm the perspective you necessarily want to design for here, but to me I'm thinking "going to this URL `/voila/render/xxx.ipynb` will trigger voila to convert the ipynb file there" and therefore it makes more sense for `ipynb` to exist (since I am performing an action on an ipynb file).

However I understand what you're saying about abstracting away the notion of an ipynb file. Maybe it's something that can be handled more clearly with documentation.

**Comment by maartenbreddels** [comment]
This is resolved in #165
