### ISSUE TITLE
Setting CWD when running as extension

### ISSUE THREAD

**Issue by shevelevs** [QuantStack/voila#118]
When running as an extension, current working directory is not the same as that of .ipynb itself, which creates problems for notebooks accessing local files. i.e. when notebook has something along the lines

```
with open("mydata.json", "r") as f:
  print(f.read())
```

Looking at the code I don't see cwd argument to executenb being passed to nbconvert.

https://github.com/QuantStack/voila/blob/f0454930469cb3fb6f59b66f58a11d34c4ca9885/voila/execute.py#L114

https://github.com/QuantStack/voila/blob/74a186f745fe609271e79de0d8a0153b6f4d3438/voila/handler.py#L55

**Comment by maartenbreddels** [comment]
Hi Sergey,

this should now be fixed in master. For voila standalone as an extension I've added tests to make sure the cwd is set. If you still find issues, please let me know.

cheers,

Maarten

**Comment by SylvainCorlay** [comment]
@shevelevs voila `0.0.10` is out. The conda-forge package should be available in an hour or so.
