### ISSUE TITLE
Pure lab-extensions can't be loaded from local filesystem

### ISSUE THREAD

**Issue by timkpaine** [QuantStack/voila#121]
Right now voila is checking the built in `nbextension` mechanisms for extensions. If you have a lab-only extension, it won't be picked up. If your notebook references it, it will be via `require` which will hit `/voila/myextension.js` which has no handler (instead of something like `/voila/static/myextension.js` or `/voila/nbextension/myextension.js`). If it successfully fails over to `unpkg`, the extension will load fine in most cases. 

We should devise a scheme for "registering" lab extensions to use and provide a mechanism to server them from disk (even if it requires extra work on the user's part, which is expected because jupyterlab only maintains web packed bundles and tarballs of its extensions).

**Comment by SylvainCorlay** [comment]
We should make a new voila template that would entirely be built from jupyterlab plugins (without the ability to dynamically load widget bundles), very much like the standalone `notebook` example in jupyterlab, but including a set number of jupyterlab extensions.

**Comment by timkpaine** [comment]
closing in favor of 
https://github.com/vidartf/phoila
