### ISSUE TITLE
Rendering issues in 0.0.9

### ISSUE THREAD

**Issue by konwiddak** [QuantStack/voila#127]
0.0.9 has been a bit of a mixed bag - some notebooks are loading perfectly, some are totally broken and others are partially broken.

I've loaded the bqplot examples https://github.com/bloomberg/bqplot/tree/master/examples

An example of a notebook that renders correctly is: /Tutorials/Brush Interval Selector

An example of a notebook that does not render correctly and is riddled with errors in the browser console is: /Advanced Plotting/Advanced Plotting notebook.

Example error:
Error: <rect> attribute height: Expected length, "Infinity".
d3.js:663 Error: <rect> attribute height: Expected length, "Infinity".
(anonymous) @ d3.js:663
(anonymous) @ d3.js:962
ft @ d3.js:968
$.each @ d3.js:961
$.attr @ d3.js:652
render @ Figure.js:128
(anonymous) @ manager-base.js:100
Promise.then (async)
(anonymous) @ manager-base.js:94
Promise.then (async)
e.create_view @ manager-base.js:93
e.display_model @ manager-base.js:74
build_widgets @ manager.js:48
async function (async)
build_widgets @ manager.js:35
renderWidgets @ WidgetApplication.js:25
async function (async)
renderWidgets @ WidgetApplication.js:21
(anonymous) @ main.js:22
load (async)
(anonymous) @ main.js:19
execCb @ require.min.js:1
check @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
emit @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
h @ require.min.js:1
completeLoad @ require.min.js:1
onScriptLoad @ require.min.js:1
load (async)
req.load @ require.min.js:1
load @ require.min.js:1
load @ require.min.js:1
fetch @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
enable @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
(anonymous) @ require.min.js:1
setTimeout (async)
req.nextTick @ require.min.js:1
o @ require.min.js:1
requirejs @ require.min.js:1
(anonymous) @ main.js:9

I've had to ensure the cache is clean to see the errors - since chrome seems to like to cache the working versions. Viewing the page in incognito mode is a good way of ensuring it's shown with a clean cache.
![voila_issue](https://user-images.githubusercontent.com/48279914/56812197-4eba5a80-6832-11e9-86d0-594c8eb3ebb1.png)

**Comment by maartenbreddels** [comment]
Which bqplot is this? I cannot reproduce this master voila and bqplot 0.11.2.

**Comment by konwiddak** [comment]
Just tried a new python environment, voila installed from master and bqplot 0.11.2 - unfortunately this doesn't fix things... Could you dump your "conda list" so I can compare environments? Thanks

**Comment by maartenbreddels** [comment]
I'm not sure I can share my env actually, could you check with voila 0.0.10, and it that didn't work I'll create a new env and share it with you.

**Comment by konwiddak** [comment]
Brilliant 0.0.10 fixes the problem. Thank you
