### ISSUE TITLE
Throw an error when a custom template is given but not found

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#129]
I found myself confused recently when I was trying to demo creating a custom template in #126 . I'd run Voila with a custom template like `--template=mytemplate`, and everything would run fine, but the final output was not the HTML I expected.

Right now, this is because Voila simply appends the custom template path to the list of templates it expects. For me, this led to confusion because I was expecting Voila to error if it didn't find my template path. Instead, it just reverted to the default template.

What do folks think about raising an error in this case, rather than reverting to default? I feel like if somebody gives a custom template, they'd rather know that the path wasn't correctly found, rather than have it silently work, but not in the way expected.

**Comment by timkpaine** [comment]
@choldgraf I agree, it should check the path to see if it exists

**Comment by SylvainCorlay** [comment]
Agreed, we should at least inform the user instead of failing silently.

**Comment by maartenbreddels** [comment]
Yes, although it will be a bit tricky. We can check if the root dir exists, but nothing more, since we don't know what the reason is for choosing the template. It could be to override custom js, for 404 pages, or the voila.tpl template. But a voila template dir does not need to have a voila.tpl.

**Comment by maartenbreddels** [comment]
#137 now checks that at least a directory with that name is found, I think that should solve this issue.
