### ISSUE TITLE
Add "localhost" to final server running message

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#130]
In lieu of automatically opening the browser with Voila, I think an easy quick fix would be to simply add `http://localhost:8866` to the print statement, rather than just `8866`. At least for some terminals, this would make it a clickable link.

**Comment by timkpaine** [comment]
This is a duplicate issue and was resolved in https://github.com/QuantStack/voila/pull/119

**Comment by choldgraf** [comment]
👍
