### ISSUE TITLE
Improve development installation

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#134]
I still haven't been able to get Voila installed locally for development. It's hard for me to tell if this is because I'm following instructions wrong because there aren't any develop installation instructions that I could find.

For example, if I do `pip install -e .` then I get the following output before the installation hangs:

```
pip install -e .
Obtaining file:///home/choldgraf/github_local/voila
^CERROR: Operation cancelled by user
^[[A^[[A(dev) choldgraf@barbecue ~/github_local/voila (master) $ pip install -v -e .
Created temporary directory: /tmp/pip-ephem-wheel-cache-sjwrv7j1
Created temporary directory: /tmp/pip-req-tracker-242owfut
Created requirements tracker '/tmp/pip-req-tracker-242owfut'
Created temporary directory: /tmp/pip-install-3akv39hm
Obtaining file:///home/choldgraf/github_local/voila
  Added file:///home/choldgraf/github_local/voila to build tracker '/tmp/pip-req-tracker-242owfut'
    Running setup.py (path:/home/choldgraf/github_local/voila/setup.py) egg_info for package from file:///home/choldgraf/github_local/voila
    Running command python setup.py egg_info
    running egg_info
    running jsdeps
    6.7.0
    6.7.0
    Installing build dependencies with npm.  This may take a while...

    > @QuantStack/voila@1.0.0 prepare /home/choldgraf/github_local/voila/js
    > npm run build:lib && webpack


    > @QuantStack/voila@1.0.0 build:lib /home/choldgraf/github_local/voila/js
    > babel src --out-dir lib

    Successfully compiled 3 files with Babel.
```

We should add developer docs so that people can get started!

**Comment by maartenbreddels** [comment]
I think it doesn't hang, it for some reason takes a long time, not sure why though.

**Comment by SylvainCorlay** [comment]
The pip installation will build the JavaScript assets which may take a long time.

Also, I don't think that development installations of python packages can install data files. So one cannot install voila with `-e`.

**Comment by choldgraf** [comment]
> Also, I don't think that development installations of python packages can install data files. So one cannot install voila with -e.

so then back to my original question, how does one install voila with the goal of developing it? :-)

**Comment by SylvainCorlay** [comment]
> so then back to my original question, how does one install voila with the goal of developing it? :-)

Modify and deploy! `pip install .` will actually remove previously installed versions and install the current state.

**Comment by choldgraf** [comment]
Hmmmm OK, well in either case, this is taking upwards of 10 minutes for the install to finish (before it hung at "Successfully compiled..."). Do y'all have to wait that long in order to test out changes normally?!

**Comment by SylvainCorlay** [comment]
> This is taking upwards of 10 minutes for the install to finish (before it hung at "Successfully compiled...")

This is weird. It takes under a minute for me. What is taking time is probably the `npm install` stage.

**Comment by choldgraf** [comment]
It seems to get past that step to me...after the "successfully compile w/ babel" message, I see a single Node process chewing up a ton of CPU but I don't see any outputs

**Comment by maartenbreddels** [comment]
> Also, I don't think that development installations of python packages can install data files. So one cannot install voila with `-e`.

To work out of the box with `pip install -e .` we also work with the share directory in the repo:
https://github.com/QuantStack/voila/blob/82b598a732fe47978b76fdfaaeebd86b852abf5b/voila/paths.py#L40

**Comment by maartenbreddels** [comment]
> It seems to get past that step to me...after the "successfully compile w/ babel" message, I see a single Node process chewing up a ton of CPU but I don't see any outputs. After some time, the process goes down to 0% CPU but the installation doesn't continue.

This smells like babel processing node_modules, I also noticed `js/.babel.config.js` is not in the repo . I'll see if I can reproduce it (and do a PR to fix this).

**Comment by SylvainCorlay** [comment]
@maartenbreddela I did not catch that. We may want to disable this when running from a source directory.

**Comment by maartenbreddels** [comment]
Yes indeed, I think we should keep it, but have a solid way of detecting if we are in a repo. See referenced issue.

**Comment by maartenbreddels** [comment]
@choldgraf could you check manually which takes longest? Babel for me is instant:
```
voila/js $ ./node_modules/.bin/babel src --out-dir lib
```
But webpack takes quite a while:
```
voila/js $ ./node_modules/.bin/webpack
```

**Comment by maartenbreddels** [comment]
`$ ./node_modules/.bin/webpack --mode=development` might also help speed it up (a factor of two here).

**Comment by choldgraf** [comment]
@maartenbreddels here are the timing results:

`./node_modules/.bin/babel src --out-dir lib` took place almost immediately

whereas

`./node_modules/.bin/webpack` took much longer...I don't actually see any output when I run it, though a node process does start. I left this running for 10 minutes before killing the process

`./node_modules/.bin/webpack --mode=development` finished in about 2 minutes.

So how would you recommend I install `voila` for development purposes? If you give me bullet points, I can try to follow them and if it works, will then follow up with a PR for dev docs

**Comment by SylvainCorlay** [comment]
Should we close this and discuss lareg bundle sizes in a separate thread?

**Comment by maartenbreddels** [comment]
Yes, we continue that on https://github.com/QuantStack/voila/issues/149

**Comment by SylvainCorlay** [comment]
Okay closing.
