### ISSUE TITLE
VBox Tabs don't work with Voila

### ISSUE THREAD

**Issue by afeiszli** [QuantStack/voila#139]
Created a VBox widget with tabs which works fine as a regular notebook, and also with the AppMode extension. However, when rendered with Voila, a user cannot switch between tabs.

tab0 = widgets.VBox(children=[uploadButton, parseInputButton, browseInputOut])
tab1 = widgets.VBox(children=[rigsN, inputOut, scheduleButton])
tab2 = widgets.VBox(children=[preferredOrderDD, animationOut])
gui = guiClass(tab0, tab1, tab2)

**Comment by SylvainCorlay** [comment]
Hi @afeiszli which verison of voila are you using?

**Comment by afeiszli** [comment]
0.0.9

**Comment by SylvainCorlay** [comment]
Could you please try with the latest version which was released earlier today (0.0.10)?


I am trying with this code, which appears to work.

```python
import ipywidgets as widgets

tab0 = widgets.VBox(children=[widgets.Button(), widgets.Button(), widgets.Button()])
tab1 = widgets.VBox(children=[widgets.Button(), widgets.Button(), widgets.Button()])
tab2 = widgets.VBox(children=[widgets.Button(), widgets.Button()])
gui = widgets.Tab(children=[tab0, tab1, tab2])
gui
```

**Comment by afeiszli** [comment]
I am using pip for installs and it's not finding 0.0.10

**Comment by afeiszli** [comment]
but I see it on PyPi...we are behind a proxy for pypi so that may be the issue.

**Comment by SylvainCorlay** [comment]
This is really weird. Voila 0.0.10 is on pypi since earlier yesterday: https://pypi.org/project/voila/#files

Are you working behind some corporate proxy for pypi?

**Comment by timkpaine** [comment]
could be pip cache too

**Comment by timkpaine** [comment]
try `pip --no-cache-dir ...`

**Comment by afeiszli** [comment]
It was the corp proxy. Got around it and got 0.0.10 installed. Tabs now work!

However, buttons do not. Maybe this should be a separate issue, but buttons get no response; looks like they're not calling the functions.

**Comment by SylvainCorlay** [comment]
> However, buttons do not. Maybe this should be a separate issue, but buttons get no response; looks like they're not calling the functions.

Are you just doing `print` statements in the button callbacks? These will typically not be displayed, unless captured in an Output widget.

**Comment by afeiszli** [comment]
Oh that is good to know...actually knowing that, I just waited a bit longer before switching tabs and it is running the function, but we get this response:

"JavaScript output is disabled in JupyterLab"

This is for a chart generated using pyplot, powered by the magics function %matplotlib notebook

**Comment by SylvainCorlay** [comment]
Ah, ok, then the issue is with the `notebook` backend to matplotlib.

**Comment by SylvainCorlay** [comment]
I recommend you try out installing `ipympl` instead and use `%matplotlib widget`.

**Comment by afeiszli** [comment]
Our charts don't render with widget which is why we switched to notebook, but that's more of an "us" problem. Thank you for your help!

**Comment by SylvainCorlay** [comment]
>  Our charts don't render with widget which is why we switched to notebook, but that's more of an "us" problem. Thank you for your help!

Please report your issue in the `ipympl` repository.

I have not been able to put any time into improving ipympl lately, but at least I will have a record of the main pain points for whenever I get some funding to push it forward.

**Comment by dcnadler** [comment]
I am having an issue with ipywidget tabs when using the "classic" template. The content from all tabs show up stacked (this does not happen with the default template, "lab").

For example, with the code from above, the output has all 8 buttons show up together, no matter which tab you're on:
![image](https://user-images.githubusercontent.com/6414742/96937600-5b4a5e00-147d-11eb-9d1b-3fef2695f02d.png)

example code from above
```python
import ipywidgets as widgets

tab0 = widgets.VBox(children=[widgets.Button(), widgets.Button(), widgets.Button()])
tab1 = widgets.VBox(children=[widgets.Button(), widgets.Button(), widgets.Button()])
tab2 = widgets.VBox(children=[widgets.Button(), widgets.Button()])
gui = widgets.Tab(children=[tab0, tab1, tab2])
gui
```
