### ISSUE TITLE
require.js is loaded after plotly needs it

### ISSUE THREAD

**Issue by leogout** [QuantStack/voila#141]
I tried to use plotly in a notebook with the following code (from plotly's doc):
```python
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
import numpy as np

init_notebook_mode()

N = 500
random_x = np.linspace(0, 1, N)
random_y = np.random.randn(N)

trace = go.Scatter(
    x = random_x,
    y = random_y
)

iplot([trace], filename='basic-line')
```
It runs well in my local jupyterlab instance:
![image](https://user-images.githubusercontent.com/9843962/57858487-724d4100-77f1-11e9-8c93-00c2986afaaf.png)

But when I try to launch it with voila it gives me a blank output cell with the error:
![image](https://user-images.githubusercontent.com/9843962/57858041-98261600-77f0-11e9-9918-2d7766654418.png)

When I inspected the template I found that plotly tries to use require.js before it gets imported (in the base template it is at the [bottom of the file](https://github.com/QuantStack/voila/blob/master/share/jupyter/voila/template/default/nbconvert_templates/base.tpl#L38))

How can I get my graph to work with voila ?

**Comment by leogout** [comment]
I just tried to put require.js in the head of the template (not ideal I know) but it works and my plot renders. I'll use a custom template for now but I would love to hear your thoughts about this.

**Comment by leogout** [comment]
If someone else stumble upon this issue, what I did to fix it is:
Copy in place the folder `venv\share\jupyter\voila\template\default` with the name `plotly`.
Edit the `plotly\nbconvert_templates\base.tpl` file that you just copied accordingly to your needs. Personnaly, I needed to load `require.js` at the top of the template.
Then, run your notebook with: `voila your_notebook.ipynb --template=plotly`

**Comment by scottlittle** [comment]
Thanks for sharing this. What was the explicit code that you used for loading `require.js` in your `base.tpl` file?

**Comment by leogout** [comment]
In the template I overrided, I used this code:
```jinja
{%- extends 'basic.tpl' -%}
{% from 'mathjax.tpl' import mathjax %}

{%- block header -%}
<!DOCTYPE html>
<html>
<head>
{%- block html_head -%}
<meta charset="utf-8" />
{% set nb_title = nb.metadata.get('title', '') or resources['metadata']['name'] %}
<title>Voila: {{nb_title}}</title>

<link rel="stylesheet" href="https://unpkg.com/font-awesome@4.5.0/css/font-awesome.min.css" type="text/css" />

{%- block html_head_js -%}

<script src="{{resources.base_url}}voila/static/jquery.min.js"></script>

<script
    src="{{resources.base_url}}voila/static/require.min.js"
    integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
    crossorigin="anonymous">
</script>

<script id="jupyter-config-data" type="application/json">
{
    "baseUrl": "{{resources.base_url}}",
    "kernelId": "{{resources.kernel_id}}"
}
</script>
{%- endblock html_head_js -%}


{%- block html_head_css -%}
{%- endblock html_head_css -%}
{%- endblock html_head -%}
</head>
{%- endblock header -%}


{% block footer %}
{% block footer_js %}
<script>
requirejs.config({ baseUrl: '{{resources.base_url}}voila/', waitSeconds: 30})
requirejs(
    [
        "static/main",
    {% for ext in resources.nbextensions -%}
        "{{resources.base_url}}voila/nbextensions/{{ ext }}.js",
    {% endfor %}
    ]
)
</script>

{% endblock footer_js %}
{{ super() }}
</html>
{% endblock footer %}
```

Do you want me to make a pr ?
