### ISSUE TITLE
widget.close() breaks in voila

### ISSUE THREAD

**Issue by jeffyjefflabs** [QuantStack/voila#143]
A colleague wrote a notebook that had a "loading" widget (similar idea to #70, but in the classic notebook interface), which he called `close()` on once everything was ready.  We tried to run the notebook in voila, but no widgets rendered at all from either before or after the `close()`.  Running voila 0.0.10, ipywidgets 7.4.2.  Chromium 71 on Ubuntu reports this error:

```
Uncaught (in promise) TypeError: Cannot read property 'state_change' of undefined
    at p.e.create_view (manager-base.js:93)
    at p.e.display_model (manager-base.js:74)
    at p.build_widgets (manager.js:49)
```

Similar result in Chrome on Windows as well as Firefox (with a less helpful error message).

Here's a minimal example:
```
# cell 1
import ipywidgets, time
loading = ipywidgets.Text(value='Loading')
loading

# cell 2
time.sleep(5)
loading.close()
ready = ipywidgets.Text(value='Ready')
ready
```

**Comment by SylvainCorlay** [comment]
It looks like the expected behavior. Voila renders the notebook once everything has been run. Hence, `close` has been called by then and there is no loading widget at all.

The `ready` widget should be rendered.

**Comment by SylvainCorlay** [comment]
Ah, I can reproduce this now. Will push out a fix soon.

**Comment by SylvainCorlay** [comment]
- `widget.close()` destroys the model, but the model_id is still in the previous cell output from nbexecute. We probably need to have the voila widget manager handle missing model ids.
