### ISSUE TITLE
WARNING:tornado.access:404 GET /voila/libwidgets.js

### ISSUE THREAD

**Issue by scottlittle** [QuantStack/voila#158]
I just updated voila via conda-forge and something broke: 
`WARNING:tornado.access:404 GET /voila/libwidgets.js (23.121.164.13) 0.50ms`
Anyone seen this before?

**Comment by scottlittle** [comment]
Reverting back to `conda install -c conda-forge voila==0.0.6` fixed it.  I'm redirecting 8866 to 80, would this affect anything?  Is voila 0.0.10 https only?

**Comment by scottlittle** [comment]
It seems like voila>=0.0.7 breaks for me.

**Comment by SylvainCorlay** [comment]
Voila 0.0.10 is not https only. I also don't see why a port redirection would affect anything.

Is there anything else custom about your setup?

**Comment by scottlittle** [comment]
After updating conda, I have to edit the kernel name in the ipynb.  Even in Viola 0.0.6, it evenually crashes.  I'm the app on Ubuntu 18.04 on AWS.

**Comment by SylvainCorlay** [comment]
Please provide some detail about the failure. There is not much we can do otherwise.

(Example notebook, what the browser shows (error 500, 404) the content of the js console, the terminal?

**Comment by scottlittle** [comment]
js console output (for 0.0.10):
```
require.min.js:1 GET http://ec2-3-89-170-144.compute-1.amazonaws.com/voila/libwidgets.js net::ERR_ABORTED 404 (Not Found)
req.load @ require.min.js:1
load @ require.min.js:1
load @ require.min.js:1
fetch @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
enable @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
(anonymous) @ require.min.js:1
setTimeout (async)
req.nextTick @ require.min.js:1
o @ require.min.js:1
requirejs @ require.min.js:1
(anonymous) @ main.js:9
require.min.js:1 Uncaught Error: Script error for "libwidgets"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:1)
    at HTMLScriptElement.onScriptError (require.min.js:1)

```

**Comment by scottlittle** [comment]
command line: `(base) ubuntu@ip-172-31-55-214:~/voila/notebooks$ cd ~/voila/notebooks/;screen voila enodo-app.ipynb`
 
terminal output:
```
[Voila] Using /tmp to store connection files
[Voila] Storing connection files in /tmp/voila_dk89f7ma.
[Voila] Serving static files from /home/ubuntu/miniconda3/lib/python3.7/site-packages/voila/static.
[Voila] WARNING | No web browser found: could not locate runnable browser.
[Voila] Voila is running at:
http://localhost:8866/
[Voila] WARNING | Notebook enodo-app.ipynb is not trusted
[Voila] Kernel started: 4f556e24-9a45-4559-825b-78d3f7f793f7
[Voila] Executing notebook with kernel: 
WARNING:tornado.access:404 GET /style.min.css.map (23.121.164.13) 0.47ms
WARNING:tornado.access:404 GET /voila/libwidgets.js (23.121.164.13) 0.34ms
```

**Comment by scottlittle** [comment]
"Solved" by starting with a fresh install of Ubuntu 18.04, pip3 installed everything, pointed 8866 to 80 using iptables, and it just worked.  I'm still running into memory issues though.  It seems like old processes hang around and slowly increase the memory until almost complete unresponsiveness and I need to reboot.  I'll close this and create another issue for that.
