### ISSUE TITLE
Rendering local images in markdown

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/voila#16]
At the moment, images in relative directories w.r.t. notebooks are not rendered.

Serving these directories would break the security model of voila, which is not supposed to expose the actual notebook content.

This raises the question of how deal with images. Could nbconvert explicitly render inline images?

**Comment by freddupont** [comment]
hello nice work on this project very impressive and potentially very useful!
In my developpement patern I copy past lots of picture in the markdown cell from PDF viewver to jupyter
When I tryed a notebook with multiple image recorded inside the notebook, the display by voila server was that each image was the same (always the first one).
I don't know if this is a bug or a feature request

**Comment by freddupont** [comment]
You will find an example notebook with 2 pictures  one blue, one yellow, its render correctly on jupyter, not on voila

https://gist.github.com/freddupont/ab5df4c5a26b2efe5152f8b72a16fe28

**Comment by maartenbreddels** [comment]
I didn't know of this functionality actually, and I can confirm that Jupyter lab and the classical notebook render it correctly, but nbconvert does not. Since we rely on nbconvert, we inherit this issue.

**Comment by SylvainCorlay** [comment]
Same, I did not know of this feature.

**Comment by maartenbreddels** [comment]
It seems the issue is fixable for nbconvert, hopefully, we can get this in the next release. I also noticed Jupyter lab is missing this feature (I could not paste an image), but maybe master has it.

**Comment by maartenbreddels** [comment]
Digging into this a bit, I think we can have a customized markdown2html filter, which instead of putting in the image src, embed the image content. 
@SylvainCorlayI think what you suggested initially (render inline image) is probably the best approach.
I think we can do this with minimal code, and possible could push this into nbconvert.

**Comment by SylvainCorlay** [comment]
> Digging into this a bit, I think we can have a customized markdown2html filter, which instead of putting in the image src, embed the image content.

This is really great news!

**Comment by SylvainCorlay** [comment]
@freddupont  this is fixed in master (and requires nbconvert master).

Your example notebook actually gave @maartenbreddels some inspiration to fix the issue!

Thanks to everyone involved.
