### ISSUE TITLE
Priorities before the dashboard workshop?

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#160]
I imagine that the workshop in Paris will be a good opportunity to tell others about Voila, get useful feedback about its approach, etc. To that extent, is there anything worth prioritizing on the tech or documentation side? If there's something I can do to polish up the docs and give potential users more of a path to learn more about Voila, try it themselves, etc, then I'm happy to spend some cycles doing this.

**Comment by jtpio** [comment]
First step: https://github.com/QuantStack/voila/pull/161 :)

**Comment by SylvainCorlay** [comment]
Thanks @choldgraf. We are trying to get a `0.1.0` out before the workshop (essentially a version upon which one can reasonably build some templates).

Also, I pushed out [voila-gridstack](https://github.com/QuantStack/voila-gridstack/), which is essentially the gridstack template that we had in `voila` originally, but split in a separate package and can serve as an example template.

**Comment by jtpio** [comment]
I think we can close this one now.

For reference here is the blog post covering the `0.1.0` release of voila and the Jupyter Community Workshop on Dashboarding: https://blog.jupyter.org/and-voil%C3%A0-f6a2c08a4a93

Thanks for opening it @choldgraf!
