### ISSUE TITLE
Example GIF doesn't show a jupyter notebook

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#169]
The Voila GIF is really nice to show off the HTML side of Voila, but it doesn't show that the dashboard was created from a notebook. I think it would be more explanatory and powerful if the GIF began with a Jupyter Notebook view, showing that the dashboard was created with python in the notebook, and then switched to the "voila" view that showed the HTML dashboard.

I'd be happy to make this myself though I'm not sure where the demo notebook is that shows off the gapminder viz.

**Comment by SylvainCorlay** [comment]
Excellent idea!

The gapminder example is in the `examples` direcrory of bqplot.

However the content of the markdown cells for that notebook should probably be changed for the purpose of the demo.

**Comment by choldgraf** [comment]
I think once #39 lands that could be a nice GIF demo. Basically:

* Open notebook in JupyterLab
* Show broad overview of notebook
* Use lab extension to "open in voila"
* Quick interactivity demo

(unless you want to highlight the CLI parts of voila more than the extension parts)

**Comment by leogout** [comment]
@SylvainCorlay I think this can be closed now that there are plenty of demo GIFs in the README ?

**Comment by choldgraf** [comment]
agreed
