### ISSUE TITLE
Add a "dry run" option

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#174]
A request that I often get from people is the ability to quickly export a notebook into a nicely-templated HTML structure they can share with others (or convert to PDF).  

Since Voila is already handling the templating infrastructure etc, I wonder if it'd be in-scope to allow a flag to tell Voila "only convert this notebook with nbconvert and dump the HTML bundle into a folder".

Something like `voila myntbk.ipynb --dont-run --output mynotebookhtmlfolder`

In this case, the notebook would be run w/ outputs captured, but would then "just" be converted to an HTML folder. In this case, opening the HTML wouldn't connect with the jupyter kernel or anything like this.

I'm still not sure if I'd consider this in or out of scope of Voila, but thought I'd run it by folks to see what they thought about it.

**Comment by timkpaine** [comment]
Isn't this just nbconvert?

**Comment by choldgraf** [comment]
@timkpaine yes and no - nbconvert is a fairly difficult tool for many folks to wrap their heads around. I find voila to be a more intuitive API and with the restricted use-case of "notebook -> HTML" I think it could be an easier sell for users.

**Comment by timkpaine** [comment]
@choldgraf what might be a cooler variant is to launch headless chrome and render voila there, then capture the html output

**Comment by maartenbreddels** [comment]
Actually, we are talking to nbconvert devs, and would like to upstream some of the voila template features, see https://github.com/jupyter/nbconvert/pull/1028
Ideally, I'd like to see most, if not all voila templates to actually be nbconvert templates that also work with voila, where depending on who runs it, it will inline resources or not.

**Comment by choldgraf** [comment]
If y'all are willing to go the upstream route, I would 100% support that!
