### ISSUE TITLE
Document deploying voila to heroku

### ISSUE THREAD

**Issue by yuvipanda** [QuantStack/voila#184]
You can deploy voila dashboards to heroku easily.

1. Have a `runtime.txt` with `python-3.7` (or similar, for your python version`
2. Put your requirements into a `requirements.txt` file. Add `jupyter_server` to it.
3. Create a `Procfile` with the following contents:
   ```
   web: jupyter extension enable voila.server_extension --sys-prefix && jupyter server --ServerApp.default_url=/voila --ip=0.0.0.0 --ServerApp.open_browser=False --port=$PORT --ServerApp.token=''
   ```
4. deploy to heroku!

When accessing the URL, this will show all the contents of your repo on heroku, and folks can navigate to whatever notebook you wish.

**Comment by yuvipanda** [comment]
If you want to open a specific notebook when users go to your URL instead of a listing of all your files, you can set the `ServerApp.default_url`. For example, to open the file `notebooks/basics.ipynb`, you can specify --`ServerApp.default_url=/voila/render/notebooks/basics`

**Comment by maartenbreddels** [comment]
Thanks for sharing this!

**Comment by SylvainCorlay** [comment]
Thanks for sharing the documentation!

**Comment by pbugnion** [comment]
Happy to write this up -- thanks @yuvipanda .

Why do you run `jupyter server` as the entry point rather than `voila` directly?

**Comment by yuvipanda** [comment]
It does not matter I think. Should work with just voila.

**Comment by pbugnion** [comment]
I got this working with a Procfile that was just:

```
web: voila --port=$PORT --no-browser
```

or:

```
web: voila --port=$PORT --no-browser basics.ipynb
```

I'll write this up in the next couple of days.

**Comment by Juanlu001** [comment]
Is this the only way to change the IP of voila? (I tried `voila --ip="*"` or `voila --ip="0.0.0.0"` and it didn't work)

**Comment by Juanlu001** [comment]
My solution for now:

```python
from voila.app import Voila


class PublicVoila(Voila):
    ip = "0.0.0.0"


if __name__ == "__main__":
    PublicVoila().launch_instance()
```

**Comment by maartenbreddels** [comment]
The way to do it is: `--Voila.ip=<ip>`, if you typed `voila --help` if would have suggested `--help-all`, but we may want to alias it with `--ip`, but that will happen automatically in the future (jupyter_server)

**Comment by jtpio** [comment]
Fixed by https://github.com/QuantStack/voila/pull/229
