### ISSUE TITLE
pip package for 0.1.0 looks broken

### ISSUE THREAD

**Issue by jeffyjefflabs** [QuantStack/voila#195]
I'm testing on top of the jupyter/base-notebook docker image.  After installing 0.1.0 via pip, I'm seeing rendering issues in the browser along with some 403 errors in the console.  Looks like some of the static files are missing in the pip package - not sure why 403 instead of 404.  The conda package looks fine, and if you switch to a pip-installed version the browser cache may save you for a while.  But the pip package for 0.1.0 is significantly smaller than previous versions as well as the conda package.

```
pip:
-rw-r--r--  1 jovyan users 6795480 Jun  5 18:14 voila-0.0.10-py2.py3-none-any.whl
-rw-r--r--  1 jovyan users 7348863 Jun  5 18:12 voila-0.0.14-py2.py3-none-any.whl
-rw-r--r--  1 jovyan users   66177 Jun  5 18:12 voila-0.1.0-py2.py3-none-any.whl

conda:
file name   : voila-0.1.0-py_0.tar.bz2
name        : voila
version     : 0.1.0
build string: py_0
build number: 0
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 5.9 MB
```

**Comment by SylvainCorlay** [comment]
Thanks! We fixed it in 0.1.1 and master.
