### ISSUE TITLE
Voila - rendered notebooks with links to each other

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/voila#21]
This should probably voila render the notebooks linked to each other.

**Comment by SylvainCorlay** [comment]
I think we can consider this is now implemented in the context of the server extension.

**Comment by vidartf** [comment]
Just for reference, which commits/PR resolved this?

**Comment by SylvainCorlay** [comment]
@vidartf it is a byproduct of https://github.com/QuantStack/voila/pull/165
