### ISSUE TITLE
Clear cell output before execute?

### ISSUE THREAD

**Issue by jeffyjefflabs** [QuantStack/voila#214]
Would it make sense for voila to clear all cell outputs before executing the notebook?  If there's an exception part of the way through execution, the rendered notebook will contain stale outputs from wherever it was executed previously, and widgets defined after the point of the exception don't render.  It's potentially confusing to the end user.  I suppose if you're using standalone voila in a production environment, you'd probably clear outputs in the notebook before saving it, but you might not think to do that with the server extension. 

Short example below.  Run both cells in normal Jupyter first, then save and launch in voila.

```
# cell 1
import datetime
print(datetime.datetime.now())
raise RuntimeError

# cell 2
import ipywidgets as widgets
print(datetime.datetime.now())
widgets.Button(description='hello')
```

**Comment by SylvainCorlay** [comment]
:+1: good catch! I agree that it would make sense to clear outputs before executing the notebook with nbexecute!
