### ISSUE TITLE
Cropped voila-square icon

### ISSUE THREAD

**Issue by jtpio** [QuantStack/voila#219]
The voila square icon seems to be cropped on the right side and doesn't look symmetrical:

![image](https://user-images.githubusercontent.com/591645/59278895-388e1f80-8c63-11e9-9f73-471b42545316.png)

https://github.com/QuantStack/voila/blob/master/docs/source/voila-square.svg

**Comment by SylvainCorlay** [comment]
@jtpio thanks! We should probably free to fix it.

Although we should not spend too much time on logos as we are working with a prefessional designer that we work on the entire visual identity of voila, and the gallery.

**Comment by SylvainCorlay** [comment]
Note: that spacing is merely the one from the font used to make that placeholder logo.

**Comment by jtpio** [comment]
This squared version is not used yet but it would be interesting to have for the templates and the JupyterLab extension.

**Comment by SylvainCorlay** [comment]
How about adding whitespace above and below so that it is not cropped instead and keepa the same spacing?

**Comment by jtpio** [comment]
Yes good point, then it has the same width and height.

Although it seems to be rendering fine in Chrome and Inkscape, which might be related to the `text` element within the svg.

For now I converted a [copy of it](https://github.com/jtpio/voila/blob/jupyterlab-extension/packages/jupyterlab-voila/style/voila.svg) to `paths` so we can start using it in #217.

**Comment by SylvainCorlay** [comment]
We should convert the object to a path in inkscape.
