### ISSUE TITLE
Deployment on Google App Engine does not show widgets

### ISSUE THREAD

**Issue by RensDimmendaal** [QuantStack/voila#221]
Deployment on google app engine does load the notebooks, but does not display the interactive widgets. It does work on heroku.

## App Engine

app.yaml:
```
runtime: python37
instance_class: F2
entrypoint: voila --port=$PORT --no-browser 
```

## Heroku

For reference, deployment at heroku as described in #184 does work: 

Procfile:
```
web: voila --port=$PORT --no-browser
```
_Originally posted by @pbugnion in https://github.com/QuantStack/voila/issues/184#issuecomment-500708132_

## Live examples
Can't guarantee they'll stay online for long:
https://playground-rdimmendaal.appspot.com/
https://test-rensd.herokuapp.com/

**Comment by jtpio** [comment]
Look like a problem with Websockets (which is required to connect to the kernel and display the widgets):

![image](https://user-images.githubusercontent.com/591645/59333665-1e068580-8cf9-11e9-927e-8f8a9006a635.png)

Is there a way on the App Engine side to enable support for Websockets?

**Comment by RensDimmendaal** [comment]
Thanks for the pointer @jtpio.
I set up a flexible engine, which since feb 2019 does supports websockets ([source](https://cloud.google.com/blog/products/application-development/introducing-websockets-support-for-app-engine-flexible-environment)).

I got it to work with the following yaml:

app.yaml
```
runtime: python
env: flex
runtime_config:
    python_version: 3
entrypoint: voila --port=$PORT --no-browser 
```

The pity is that flexible environments are always on, which makes them a lot more expensive.
Hopefully the information above will be useful to someone else as well.

**Comment by jtpio** [comment]
@RensDimmendaal thanks for getting back and glad to hear it worked!

We're planning to document several ways to deploy Voila apps using different cloud providers.
If you feel like writing about your experience with App Engine it would be really great to have it summarized in an issue (similar to https://github.com/QuantStack/voila/issues/184). Thanks!
