### ISSUE TITLE
Option to exclude Markdown cells

### ISSUE THREAD

**Issue by DougRzz** [QuantStack/voila#24]
I would like the option to exclude markdown cells in Voila.  In some of my notebooks have several markdowns cells to help me navigate the notebook but these would be a distraction for the end user.  

Does Voila use nbconvert to render the markdown cells?  If so, there is an option in nbcovert to exclude markdown.  Can this be easily enabled in Voila?

nbconvert command to exclude markdown:
`!jupyter nbconvert --to python 'example.ipynb' --stdout --TemplateExporter.exclude_markdown=True`

**Comment by SylvainCorlay** [comment]
Indeed, I would like to expose all `HTMLExporter` configurable values in a meaningful way!
