### ISSUE TITLE
Work with non-existing kernels

### ISSUE THREAD

**Issue by maartenbreddels** [QuantStack/voila#259]
The notebook is quite forgiving when the kernel name does not match the kernels installed, while voila give a 500 (http) error, I guess we can copy the logic of the classical notebook or lab on how to deal with that.

**Comment by SylvainCorlay** [comment]
+1

this hit me quite a few times already

**Comment by maartenbreddels** [comment]
Jupyter notebooks seems to handle this client side here:
https://github.com/jupyter/notebook/blob/e498de6775b3de57f5ff827e562c179b17893064/notebook/static/notebook/js/kernelselector.js#L214

My guess is that lab has a similar path.

Question: should we solve this in voila or nbconvert?

**Comment by maartenbreddels** [comment]
Continuing discussion in #309
