### ISSUE TITLE
Dark theme with ipyleaflet

### ISSUE THREAD

**Issue by jtpio** [QuantStack/voila#276]
Using ipyleaflet with voila seems to be breaking the dark theme:

![ipyleaflet-dark-theme](https://user-images.githubusercontent.com/591645/60506421-17e74180-9cc6-11e9-91e4-13e2b5a2ae24.gif)

To reproduce:

- `conda create -n test -c conda-forge voila ipyleaflet`
- Fetch an ipyleaflet notebook, for example: https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/WidgetControl.ipynb
- `voila --theme=dark`
- render the notebook with voila

cc @martinRenou @maartenbreddels I think there is the same behavior with `ipysheet`. It's probably related to the way the JLab themes are handled? https://github.com/jupyter-widgets/ipyleaflet/pull/383 and https://github.com/QuantStack/ipysheet/pull/80

**Comment by SylvainCorlay** [comment]
Thanks, will open a PR. I know the fix :)

**Comment by jtpio** [comment]
Fixed in ipyleaflet 0.11.1 with https://github.com/jupyter-widgets/ipyleaflet/pull/400
