### ISSUE TITLE
Graphs generated by offline plotly not visible

### ISSUE THREAD

**Issue by lindy255** [QuantStack/voila#284]
I'm trying to run my notebook, using plotly.offline with voila, following minmal code:

```import plotly.offline

to_draw = [{
            'y': [1,2,3,4], 
            'mode': 'lines', 
            'name': 'name'  }]
                
fig = {
            'data': to_draw,
            'layout': {
                'xaxis': {'title': 'x'},
                'yaxis': {'title': "y"}
            }
        }

plotly.offline.iplot(fig)
```
It works in jupyter notebook, but doesn't in voila ( no plot visible). Is there any way to display interactive plotly graph? If yes, can anyone suggest how to do this with voila?

**Comment by DougRzz** [comment]
@lindy255,
Convert your Plotly figure to a widget. https://plot.ly/python/figurewidget/

**Comment by lindy255** [comment]
@DougRzz  - thanks, that solves the problem. Actually I was trying also to interactively change some parameters of the plot using ipywidgets, like this:
```
@interact
def slide(x=(1,10)):
    to_draw = [{
                'y': [1,2,3,x], 
                'mode': 'lines', 
                'name': 'name'  }]

    fig = {
                'data': to_draw,
                'layout': {
                    'xaxis': {'title': 'x'},
                    'yaxis': {'title': "y"}
                }
            }
    w = go.FigureWidget(fig)
    
    return w 
```

But I'm getting "404 GET /voila/plotlywidget.js " from voila. Am I doing something wrong or is this kind of use of widgets not possible?

Many thanks in advance!

**Comment by DougRzz** [comment]
I can't remember the syntax exactly but you can edit y values in an exisiting plot. So you could create the figure widget then do:

```python 
x =5
w.data.y = [1,2, 3,x]
```
Put something similar to the above in the function with the interact decorator.  Does that help?

**Comment by lindy255** [comment]
Thanks, that solved all my problems!
