### ISSUE TITLE
$ undefined

### ISSUE THREAD

**Issue by maartenbreddels** [QuantStack/voila#288]
Now that jquery has left the page, we get many warning, that $ is not defined, from:
```
<script type="text/javascript">
var element = $('#3f949d58-54e6-4a0e-905e-e8382b9e53e4');
</script>
```
Which is something nbconvert outputs. Can we simply get rid of this in the voila template? I have no idea what this should do.

**Comment by SylvainCorlay** [comment]
I think this should be removed.

**Comment by jtpio** [comment]
It looks like it's not doing anything special indeed.

**Comment by jtpio** [comment]
Ah there is still a reference in the error.html for the default template:

https://github.com/QuantStack/voila/blob/ce9f955d427728bf2b5b242ebbceb243079dcdd9/share/jupyter/voila/templates/default/templates/error.html#L36
