### ISSUE TITLE
Voila phosphor widget 

### ISSUE THREAD

**Issue by timkpaine** [QuantStack/voila#289]
As a user, I'd like to embed multiple voila instances on the same page in phosphor widgets without an iframe (my dashboard project currently uses an iframe) and without duplicate loading of resources.

This sits somewhere between voila as a jupyterlab extension and voila standalone. With this, you can construct multi-notebook dashboards, or even do parameterized (e.g. papermilled) dashboards composed of multiple instances of the same notebook.

**Comment by timkpaine** [comment]
@vidartf

**Comment by vidartf** [comment]
I'm exploring some of this in https://github.com/QuantStack/voila/pull/238. There are some major questions to resolve though:
- If we want to support rendermime, we need to have a `JupyterFrontEndApp`. We would probably need to implement our own to ensure we get a shell that doesn't use hard-coded DOM ids
- Should we try for one shared app instance? Or would we want to allow for multiple versions of the same widget package on the page (max one per kernel though)? Could we do that with one registry?
- The partial rendering work might conflict with this? I have never tried to put a lab/phosphor app on a page while it is loading. I think there might be some weird corner cases..

**Comment by timkpaine** [comment]
closing in favor of
https://github.com/vidartf/phoila
