### ISSUE TITLE
Pass voila parameters through a REST api

### ISSUE THREAD

**Issue by choldgraf** [QuantStack/voila#299]
I've been getting a lot of questions from people asking how they can share Voila dashboards that can both remove the code **and** show the code depending on the notebook. I know that Voila has a parameter for whether to strip the outputs, but AFAIK this is invoked when `voila` is called (or when the Jupyter server is started).

It would be useful if one could pass options when Voila is being used as part of the Jupyter server (e.g. within Binder). Something like:

`myhub.org/voila/pathtonotebook?parameter=value`

and then this could control some of the behavior from within a running jupyter session. This could then be used to control whether code is hidden or not, e.g.:

`myhub.org/voila/pathtonotebook?stripOutputs=true`

or

`myhub.org/voila/pathtonotebook?stripOutputs=false`

Does something like this exist? And if not, how do folks feel about it?

**Comment by timkpaine** [comment]
#105

**Comment by SylvainCorlay** [comment]
Absolutely.

I think that if the strip_sources is set to True in the backend, the source
should not be sent at all to the front-end, as a security / privacy feature.

If strip_sources is set to False, the default template should have a means
to toggle its visibility.

**Comment by choldgraf** [comment]
@timkpaine you are always better at finding duplicate issues than I am :-)

ok I'll close this so we can focus conversation on #105, will copypaste over from here
