### ISSUE TITLE
requirejs timeouts when loading libwidgets

### ISSUE THREAD

**Issue by Juanlu001** [QuantStack/voila#31]
Experimenting with voila I noticed that I usually get a require.js timeout the first time I open the page:

```
Error: Script error for "libwidgets"
http://requirejs.org/docs/errors.html#scripterror
```

However, it's gone when I refresh. If I disable the cache in my developer tools, I keep getting the error. Is this what #4 is trying to solve?

**Comment by Juanlu001** [comment]
The answer was changing the `require.js` configuration here:

https://github.com/QuantStack/voila/blob/7613e813a0a421ebe0d0c318fb0e2f92b5dc36ca/voila/nbconvert_templates/base.tpl#L44

**Comment by maartenbreddels** [comment]
I was about to write that, you can configure that indeed. Could you share it here, I lost track of my local changes for that.

**Comment by Juanlu001** [comment]
Sure, it would be something like:

```html
<script>requirejs.config({ baseUrl: '{{resources.base_url}}voila/static',
                           waitSeconds: 20 })</script>
```

taken from https://requirejs.org/docs/api.html#config-waitSeconds
