### ISSUE TITLE
Problem with running notebook with Voila

### ISSUE THREAD

**Issue by stephjuneau** [QuantStack/voila#311]
The attached notebook does not render with Voila. It needs the astroML package (https://www.astroml.org/user_guide/installation.html). 

[Large_Scale_Structure_of_the_Universe-Short.ipynb.zip](https://github.com/QuantStack/voila/files/3403414/Large_Scale_Structure_of_the_Universe-Short.ipynb.zip)

**Comment by maartenbreddels** [comment]
Hi Stephanie,

thanks for the issue. Could you share the stack trace, just in case I have trouble reproducing, and for people to compare issues?

cheers,

Maarten
