### ISSUE TITLE
labextension 403

### ISSUE THREAD

**Issue by mpilosov** [QuantStack/voila#315]
I got the recent JLab update and updated voila as well, I noticed the extension and tried to install it, only to find 403 errors every time I tried to render the notebook with voila. I've tried this locally and on a Jupyterhub instance, but there I got 404. I think in that case it's a matter of having used DockerSpawner. 

But what to do about the 403 error? After I enable the extension, what else is left? I installed using pip

**Comment by jtpio** [comment]
Thanks @mpilosov for the report.

The extension seems to be working fine on Binder (which uses KubeSpawner) with [this gist](https://gist.github.com/jtpio/c90174dd200b457a5a6505deedf8b17a): https://mybinder.org/v2/gh/jtpio/c90174dd200b457a5a6505deedf8b17a/master?urlpath=lab

Could it be that the serverextension was not installed correctly with pip? What does `jupyter serverextension list` return?

**Comment by LuisFRoch** [comment]
@mpilosov This may fix it:
 pip install -e git+git://github.com/QuantStack/voila.git@master#egg=voila

**Comment by mpilosov** [comment]
@LuisFRoch no luck on that. 
@jtpio thanks, I tried the link before and didn't have any luck. I've never seen a multi-part gist like that! very cool. That might be a useful repo to set up as a "template" (new feature) for voila applications. I'll dig through the environment differences between binder and where I'm trying to get this working... 

```
    voila  enabled 
    - Validating...
      voila 0.1.9 OK
```

**Comment by mpilosov** [comment]
@jtpio oh... weird, okay, a shut-down of the hub seemed to do it after running @LuisFRoch's instructions... this was me testing on a local machine. I'll get around to testing it with the Hub/Spawner and post my results here before closing the issue.

**Comment by mpilosov** [comment]
yay it works in the dockerized container too. thanks so much for the help!
