### ISSUE TITLE
Rotating dashboards

### ISSUE THREAD

**Issue by gramster** [QuantStack/voila#332]
It would be great to be able to set up several dashboard pages, and have Voila rotate through them. One of them could be a "refresher" which updates the backing data. I am thinking of a case where this is an unattended but self-updating dashboard for a wall-mounted TV in a team room.

This could be done instead by a shell script and several separate notebooks being run in turn I expect, so it's not a high-priority ask.

**Comment by jtpio** [comment]
@gramster this use case sounds similar to https://github.com/QuantStack/voila/issues/333.

This should already be achievable at the moment by using a couple of browser extensions (auto-refresh and cycling through open tabs).

Another way to trigger the refresh would be to add a bit of logic in a custom template as mentioned in https://github.com/QuantStack/voila/issues/333#issuecomment-516299584.

**Comment by DougRzz** [comment]
@gramster   It might be worth having a look at https://github.com/mariobuikhuizen/ipyvuetify

Ipyvuetify might make it possible to implement a beautiful Jupyter Widgets carousel solution similar to something like this  https://vuetifyjs.com/en/components/carousels#cycle

**Comment by gramster** [comment]
Thanks for the suggestions; I'll take a look at these options.

**Comment by sergio-chumacero** [comment]
Yet anothoer option is to place your dashboards in an ipywidgets tab/accordion and start a thread that cycles through them. 

The thread will start and die with your app, so no setup/cleanup is needed.
You could also add a play/pause button that is observed by the thread. The following snippet should make the idea clearer.

```python
import time
import threading
import ipywidgets as widgets

dashboards = [widgets.HTML(value=f'Dashboard {i}') for i in range(3)]
tab = widgets.Tab(children=dashboards)

for i in range(len(dashboards)):
    tab.set_title(i,str(i))
    
start_pause_btn = widgets.ToggleButton(
    description='start',
    icon='play'
)

def on_button_change(change):
    d = 'pause' if change['new'] else 'play'
    start_pause_btn.description = d
    start_pause_btn.icon = d
    
start_pause_btn.observe(on_button_change,names='value')

def watch_carousel():
    while(True):
        time.sleep(1)
        if start_pause_btn.value:
            tab.selected_index = (tab.selected_index + 1) % len(dashboards)
        else:
            pass

carousel_thread = threading.Thread(
    target=watch_carousel,
    daemon=True,
)
carousel_thread.start()
widgets.VBox([tab,start_pause_btn,])
```
![carouserl](https://user-images.githubusercontent.com/39228828/62416490-b2121080-b609-11e9-84ef-589977a74de1.gif)

**Comment by maartenbreddels** [comment]
@DougRzz the Carousel was a great idea. FYI, this will give you an carousel:
```python
import ipyvuetify as v
import ipywidgets as widgets

tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))

accordion = widgets.Accordion(children=[widgets.IntSlider(), widgets.Text()])
accordion.set_title(0, 'Slider')
accordion.set_title(1, 'Text')
accordion
    
tab_nest = widgets.Tab()
tab_nest.children = [accordion, accordion]
tab_nest.set_title(0, 'An accordion')
tab_nest.set_title(1, 'Copy of the accordion')
tab_nest

v.Carousel(children=[
    v.CarouselItem(children=[
        tab_nest
    ]),
    v.CarouselItem(children=[
        tab
    ]),
    
], cycle=True)
```
Note that there are some css issues with mixing ipyvuetify and ipywidgets.

With two solutions, I think we can close this issue, feel free to reopen if not.

**Comment by maartenbreddels** [comment]
Another solution could be a template, where the tree.html would show the notebooks in the folder in the carousel.
