### ISSUE TITLE
position voila dashboard components side by side on MyBinder

### ISSUE THREAD

**Issue by cornhundred** [QuantStack/voila#336]
Hi, I was able to get a fork of the [gaussian-density](https://github.com/voila-gallery/gaussian-density) repo working on MyBinder and add my custom widget [Clustergrammer2](https://github.com/ismms-himc/clustergrammer2) to the dashboard - but I want to know if there is an easy way to position the two elements side-by-side.

I can do this when I run voila locally and use `--template=gridstack`. But is it possible to do run gridstack template on MyBinder? Or initialize the positions of the dashboard components (e.g. using cell metadata?).  

Repo link: 
https://github.com/ismms-himc/gaussian-density

My Binder link to voila dashboard with Clustergrammer2: 
https://mybinder.org/v2/gh/ismms-himc/gaussian-density/master?urlpath=voila%2Frender%2Findex.ipynb

**Comment by maartenbreddels** [comment]
This example repo might help out:
https://github.com/maartenbreddels/voila-demo

And yes, looking at the template:
https://github.com/QuantStack/voila-gridstack/blob/503ef739337507b33c2f9a135caa8efb8821a54e/share/jupyter/voila/templates/gridstack/nbconvert_templates/voila.tpl#L126
You can figure out how to add metadata to control the size.

Note that this may change in the future, so if you want this to work in the future you may want to put strict version matches.

**Comment by cornhundred** [comment]
Thanks @maartenbreddels for the advice, that looks like what I need.

I also tried using `HBox` from ipywidgets, which seems to give me the desired side-by-side output in the dashboard. I'll post an updated link once I have it set up.
