### ISSUE TITLE
Development environment, can't enable nbextension

### ISSUE THREAD

**Issue by marketneutral** [QuantStack/voila#341]
I'm following the developer environment setup [here](https://github.com/QuantStack/voila/blob/master/CONTRIBUTING.md#setting-up-a-development-environment). When I run `jupyter nbextension enable voila --sys-prefix`, I get

```
Enabling notebook extension voila...
      - Validating: problems found:
        - require?  X voila
```

With success, I can run Jupyter notebook; I can run `voila` from the command line; I can point the browser to `http://localhost:8888/voila/tree`.

I don't see the Voila button in the notebook bar however. Running ` jupyter nbextension list` gives

```
Known nbextensions:
  config dir: /home/jlarkin/.jupyter/nbconfig
    notebook section
      snippets/main disabled
      freeze/main  enabled
      - Validating: problems found:
        - require?  X freeze/main
  config dir: /home/jlarkin/.conda/envs/voila/etc/jupyter/nbconfig
    notebook section
      voila  enabled
      - Validating: problems found:
        - require?  X voila
```

Ultimately, I am simply looking to add another button that copies the active notebook from the current directory to another directory (a poor man's "publish"). I expect I work in the `.../static/extension.js` file, but before even trying with that, I would like to see if I can see the Voila button already defined there.

**Comment by jtpio** [comment]
@marketneutral could you try the following:

```
jupyter nbextension install voila --sys-prefix --py
jupyter nbextension enable voila --sys-prefix --py
```

**Comment by marketneutral** [comment]
That worked! Thank you.
