### ISSUE TITLE
TypeError: Cannot read property 'kernelChanged' of undefined

### ISSUE THREAD

**Issue by hainm** [QuantStack/voila#345]
Hi all, I've tried the latest voila from conda-forge (0.1.9) with the simple notebook

```    import ipywidgets,
    print(ipywidgets.__version__)
    ipywidgets.Text(\"hello there\")
```

but getting below error in JS console.
```
manager.js:61 Uncaught (in promise) TypeError: Cannot read property 'kernelChanged' of undefined
    at new M (manager.js:61)
    at new t.WidgetManager (manager.js:44)
    at main.js:14
```

**Comment by jtpio** [comment]
Thanks @hainm.

Mind sharing the notebook? It could related to the notebook metadata (just a guess for now)

**Comment by hainm** [comment]
hi @jtpio, sure. Below is the full content of the notebook

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "42cfb76ec3c540118666f123ee0d37d5",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Text(value='hello there')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import ipywidgets\n",
    "\n",
    "ipywidgets.Text(\"hello there\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by hainm** [comment]
I am not sure if this is related, I am using ipywidgets 7.5.1
If I recalled correctly, I was able to use voila nicely in the past (may be with ipywidgets 7.4.x)

**Comment by jtpio** [comment]
Just tested with this notebook on [Binder](https://mybinder.org/v2/gh/QuantStack/voila/stable?urlpath=voila%2Ftree) (which is using voila 0.1.9 and ipywidgets 7.5) and it seems to be working fine.

Maybe worth trying in a fresh new conda environment?

Also the voila frontend (which gives this error) was changed in 0.1.8, so maybe the old version is still cached by the browser and clearing it would help?

**Comment by hainm** [comment]
hi, still not working.

Below are my exact commands
```
conda create -n voila python=3.7 && source activate voila
conda install voila -c conda-forge -y
conda install -c conda-forge ipywidgets=7.5 -y
```

My desktop is centos7.

**Comment by hainm** [comment]
> Also the voila frontend (which gives this error) was changed in 0.1.8, so maybe the old version is still cached by the browser and clearing it would help?

I did not clean the cache but tried with different browser (that was not with voila before) and I can see the widgets. Yeah, I think that's cache issue. Thanks.

**Comment by jtpio** [comment]
Good to hear.

Another way to temporarily disable the cache is to open the dev tools and check that setting, and then reload the page:

![image](https://user-images.githubusercontent.com/591645/62730960-60aabc80-ba21-11e9-83b7-825bf1fbda5d.png)
