### ISSUE TITLE
Document sharing voila notebooks with ngrok

### ISSUE THREAD

**Issue by jtpio** [QuantStack/voila#347]
Something that falls under the "Deploying / Sharing" category and can be worth documenting is using voila together with [ngrok](https://ngrok.com).

The typical workflow would be:
- work locally on a notebook
- start a standalone voila instance locally with: `voila example.ipynb`
- open a tunnel in another terminal: `ngrok http 8866`
- copy the `ngrok` link
- send the link

Here is a quick demo screencast:

![ngrok](https://user-images.githubusercontent.com/591645/62892450-9533b680-bd48-11e9-8fc7-19d82d9c6710.gif)

Maybe the fastest way to share a notebook over the internet?

**Comment by faKerouhWTG** [comment]
Hi, I confirm that it is the faster way to share notebooks but its duration is only 2H and if you close voila, the link is lost. Is there any a way to overcome theses limitations ?
