### ISSUE TITLE
Can voila be used with JupyterLab/JupyterHub?

### ISSUE THREAD

**Issue by dclong** [QuantStack/voila#35]
Does voila support JupyterLab/JupyterHub?

**Comment by SylvainCorlay** [comment]
- JupyterHub can serve voila, this is how the binder works.
- JupyterLab does not really have anything to do with voila :)

**Comment by dclong** [comment]
@SylvainCorlay 

What does it mean that "JupyterLab deos not really have anything to do with voila"? Does voila work in JupyterLab?

**Comment by SylvainCorlay** [comment]
I am just a bit confused by what you mean by voila to "work with JupyterLab". Notebooks authored in Jlab and in the classic notebook have the same format and are supported by voila.

**Comment by dclong** [comment]
I mean as a server extension, does voila work with JupyterLab?

**Comment by maartenbreddels** [comment]
Yes, that should work, if not, let us know. Cheers

(from mobile phone)

**Comment by DYSpider13** [comment]
Sorry to reopen the issue. 
I'm trying to work with Voilà on JupyterHub but still get error 500. Followed some pieces of advice like updating pygment, but still the same error. 

Any lead on the reason of the issue ? 

Best regards,

**Comment by SylvainCorlay** [comment]
Responding on the other issue.

500 error is basically anything in the backend, from an error running the notebook to a missing package.

We will work on producing better clues in the error 500 page without exposing the content of the notebook should it fail to run.
