### ISSUE TITLE
Can Voila Work With ParamNB?

### ISSUE THREAD

**Issue by gfleetwood** [QuantStack/voila#350]
Hi, 

The library [paramnb](https://github.com/ioam/paramnb) has a feature where it allows for the execution of the next n cells in a notebook when a widget is updated or a button is pressed. I tried to replicate this behavior in voila's server extension mode but it didn't work. I just wanted to check whether it's possible to replicate this with voila.

I'm using paramnb instead of ipywidgets because the logic of selecting a range based on an object generated dynamically by text input is easier to manage.

Here's a minimal example (the next_n argument runs the next n notebook cells): 

```
!pip install paramnb
```

```
import param
import paramnb
```

```
class Options(param.Parameterized):    
    x = param.String(default="test",doc="A string")

# Runs the next two cells when the button is pressed.
print("Enter a word")
paramnb.Widgets(Options, next_n = 2, continuous_update = False, button = True)
```

```
length = len(Options.x)
```

```
class Options2(param.Parameterized): 
    a = param.Integer(default = 0, bounds = (0, length - 1), 
                                  allow_None = False, doc = 'A')
    
# Runs the cell below once the widget is updated.
paramnb.Widgets(
    Options2, next_n = 1, on_init = True, continuous_update = True, button = False)
```

```
print(Option2.a)
```

**Comment by jtpio** [comment]
@gfleetwood thanks for bringing this.

I haven't used paramnb but briefly looking at the code it looks like the cells are executed client side from the notebook: https://github.com/ioam/paramnb/blob/08733793a1022b21cdb9b3770a71f63188ad92da/paramnb/__init__.py#L46

Voila disallows execution requests so this is not going to work indeed.

It should be possible to achieve a similar result by using ipywidgets only.

**Comment by gfleetwood** [comment]
Thanks for looking into it.
