### ISSUE TITLE
control output widget from interact

### ISSUE THREAD

**Issue by jkerfs** [QuantStack/voila#355]
Minimal example to cause error:
```
#cell 1
import ipywidgets as widgets
from ipywidgets import interact
from IPython.display import clear_output
output1 = widgets.Output()
output1

#cell 2
def toggle_text(val):
    with output1:
        print(val)
interact(toggle_text, val=widgets.ToggleButton(description='Toggle text'))
```

```
Traceback (most recent call last):
...
File "/opt/anaconda3/lib/python3.7/site-packages/voila/execute.py", line 79, in set_state
    del self.executor.output_hook[self.msg_id]
KeyError: 'e7108564-b1a38beaf451e1c7095357b2'
```

I can fix this problem by changing https://github.com/jkerfs/voila/blob/master/voila/execute.py#L79
to 
```
if self.msg_id in self.executor.output_hook:
    del self.executor.output_hook[self.msg_id]
```

Is anyone familiar with why this would be happening?  Am I using interact and output widget wrong or should we include that output hook check shown above to resolve it?

**Comment by maartenbreddels** [comment]
I can confirm this is a bug, that seems to be the solution, but I want to dig a bit into why this is happening. Thanks for opening the issue!
