### ISSUE TITLE
Voila mode button/option

### ISSUE THREAD

**Issue by maartenbreddels** [QuantStack/voila#36]
Like appmode, https://github.com/oschuett/appmode it would be good to have a button or option in the menu bar for the classical notebook to open a notebook in voila (also make voila more 'visible'). For Jupyter lab, we could add a command to the command palette, and possibly add it to the menu.

**Comment by jtpio** [comment]
That would be great indeed.

So the idea would be to open a new tab pointing to `/voila/render/notebook`?

**Comment by DougRzz** [comment]
Could Voila serve a Rise slideshow? This could allow Voila to make use of the Rise slide type dropdown menus and enable the user to specify the cells to serve.

**Comment by timkpaine** [comment]
@maartenbreddels it would be cool to add a "Share with voila" option. Basically a button you click that generates a unique (and maybe token-protected) link that you could send to someone else and have them (and only them) see. And also have an option to share a publicly viewable version.

**Comment by maartenbreddels** [comment]
> So the idea would be to open a new tab pointing to `/voila/render/example`?

yes, that's now implemented.



> Could Voila serve a Rise slideshow

I think it could, but that would use a different template. Since we use nbconvert, and nbconvert already has a template for this, it is good to keep in mind. Maybe a really small template is required.



> @maartenbreddels it would be cool to add a "Share with voila" option.

Absolutely, that's is what I have in mind for the long term. I think the token idea would be something that could be implemented in jupyter_server, and then voila could make use of this.

**Comment by SylvainCorlay** [comment]
I think that having a voila template to generate slides and work with rise is a great idea. We should probably track this with a separate issue and have a discussion with Damian on this.

**Comment by maartenbreddels** [comment]
Yes, let us close this issue, feel free to open new issues @DougRzz and @timkpaine
