### ISSUE TITLE
Missing shortcut to launch voilà render in JLab notebooks

### ISSUE THREAD

**Issue by adriendelsalle** [QuantStack/voila#376]
Hello!
Thanks again for this great work!

Description of the missing feature
--
After installing the `voilà` package from conda-forge, the `@jupyter-voila/jupyterlab-preview` labextension and serverextension, the shortcut `[v]` in the notebooks opened with JLab is missing.
It was shown [here](http://www.youtube.com/watch?v=VtchVpoSdoQ&t=8m50s) during the 2019 Scipy conference about dashboarding.
![voila_labextension](https://user-images.githubusercontent.com/27348745/64132095-5506a780-cdcd-11e9-9d9a-46cc26693ff9.png)

The shortcut is displayed as expected in the classic notebook.
![nb_shortcut](https://user-images.githubusercontent.com/27348745/64132075-33a5bb80-cdcd-11e9-8f7e-dfdd7d64c1e7.png) 

Env
--
My O/S is Ubuntu 18.04.
I'm using conda==4.7.11

package | version | build | repo
--- | --- | --- | ---
jupyter_client | 5.3.1 | py_0  | conda-forge
jupyter_core          |      4.4.0               |         py_0  |    conda-forge
jupyter_server        |      0.1.1       |               py37_0    |  conda-forge
jupyterhub        |          1.0.0       |               py37_0   |   conda-forge
jupyterlab           |       1.1.1            |            py_0   |   conda-forge
jupyterlab_pygments     |    0.1.0       |                 py_0  |    conda-forge
jupyterlab_server        |   1.0.0           |             py_1   |   conda-forge
notebook          |         6.0.0              |       py37_0   |  conda-forge
voila               |       0.1.10              |        py_0   |  conda-forge

JupyterLab v1.1.1
Known labextensions:
   app dir: /home/adrien/miniconda3/envs/jupy/share/jupyter/lab
        @jupyter-voila/jupyterlab-preview v0.1.1  enabled  OK
        jupyter-materialui v0.1.1  enabled  OK

config dir: /home/adrien/miniconda3/envs/jupy/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 1.1.1 OK
    voila.server_extension  enabled 
    - Validating...
      voila.server_extension  OK
    voila  enabled 
    - Validating...
      voila 0.1.10 OK

Known nbextensions:
  config dir: /home/adrien/miniconda3/envs/jupy/etc/jupyter/nbconfig
    notebook section
      jupyter-materialui/extension  enabled 
      - Validating: OK
      voila/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK

Thanks a lot for your response!

**Comment by jtpio** [comment]
Thanks @adriendelsalle for the report.

It appears to be a problem with JupyterLab 1.1.0, and the icon seems to be displayed fine with JupyterLab 1.0.x.

If you hover over where the icon should be, do you get a tooltip?

![image](https://user-images.githubusercontent.com/591645/64153132-7481ec80-ce2e-11e9-92eb-edf7874514c3.png)

 In the meantime temporarily downgrading to 1.0 could be an option?

**Comment by adriendelsalle** [comment]
Hi @jtpio 

You're right, the shortcut is just not well displayed but my I hover it shows me the title!
![voila_invisible_shortcut](https://user-images.githubusercontent.com/27348745/64155760-bd886f80-ce33-11e9-9108-73cefebe5f1f.png)

Sure I can downgrade to 1.0.*. It's weird because the 1.1 release of `JLab` is not supposed to introduce breaks. I'm not familiar with labextensions but will try to investigate.

**Comment by jtpio** [comment]
You're right it shouldn't introduce breaks.

There was a big refactoring of how icons are handled in `1.1` so this might be a side effect of it. We need to fix the voila extension to work with `1.1`.
