### ISSUE TITLE
Can't serve notebooks in other directories

### ISSUE THREAD

**Issue by timkpaine** [QuantStack/voila#59]
For example, if i'm in `/tmp/dir1` and try to run `voila tmp/dir2/bqplot.ipynb` i'll get a 404 `No such file or directory tmp/dir2/bqplot.ipynb`

**Comment by maartenbreddels** [comment]
This should be fixed once #42 is merged, more specifically in https://github.com/QuantStack/voila/pull/42/commits/3bbad075b83ab89263842c4e4f62a0c770b1efa5

Thanks for reporting!

**Comment by timkpaine** [comment]
Thanks!
