### ISSUE TITLE
Binder broken

### ISSUE THREAD

**Issue by Carreau** [QuantStack/voila#66]
Just show a file structure can't get anything interactive.

Sorry for short issue, in a meeting, on my phone.

**Comment by SylvainCorlay** [comment]
Hum, this appears to be working on my side.

**Comment by Carreau** [comment]
Here is a screenshot from the computer I'm on, the example work though from this computer. I'll investigate on the other. 
I'm not sure if the welcome screen is supposed to look like that either, or be themed.  
![screen shot 2019-02-08 at 8 55 19 am](https://user-images.githubusercontent.com/335567/52493025-5c3f3d00-2b7f-11e9-9b4b-2d8f7f7a4f47.png)

**Comment by SylvainCorlay** [comment]
This is the expected behavior :)

These are links. We need to give some styling love to the directory view.

**Comment by Carreau** [comment]
Ok. Good to know. I'm pretty sure I was not able to get it to run on another computer either, but i'm going to assume this is the other computer fault.

**Comment by SylvainCorlay** [comment]
I am confused. Your screenshot shows it working.
