### ISSUE TITLE
Loading screen while widgets load

### ISSUE THREAD

**Issue by timkpaine** [QuantStack/voila#70]
There is a brief period when we just show the empty white box while the widgets load/python executes. We should think of a good loading screen and find a way to hook it in. Initial thought is wait for `kernel-ready`, but its conceivable users could program an infinite loop in their last cell.

**Comment by maartenbreddels** [comment]
This is demonstrated in #60, but I will split off the progressive part. It works by first sending the voila.html template (a regular jinja template), flush it to the browser (so it can do progressive rendering). After this, the kernel is started, the notebook executed and the nbconvert template rendered and send to the browser.
Sounds good?

**Comment by SylvainCorlay** [comment]
Closing as subperseded by discussions on progressive rendering.
