### ISSUE TITLE
generated response includes 12k lines of css

### ISSUE THREAD

**Issue by jf---** [QuantStack/voila#77]
I noticed that when hosting a notebook with voila, that in the initial response, 12k lines of `bootstrap css` is included. While most `js` code is cached, this initial response is not and takes little under 3.00 seconds to complete. About 95% of the response data is the `css` code. It seems low hanging fruit to just link the dependency ( as is done for font-awesome ) or is served as a separate file, such that the browser can perform caching.

this applies to the template:

`voila/share/jupyter/voila/template/default/nbconvert_templates/voila.tpl`

here the [`css code`](https://github.com/QuantStack/voila/blob/340cd65776ac75cf864c0f219de3f696be5c28c7/share/jupyter/voila/template/default/nbconvert_templates/voila.tpl#L6) is inlined in the template 

whereas

`voila/share/jupyter/voila/template/gridstack/nbconvert_templates/voila.tpl`

[inlines](https://github.com/QuantStack/voila/blob/340cd65776ac75cf864c0f219de3f696be5c28c7/share/jupyter/voila/template/gridstack/nbconvert_templates/voila.tpl#L4) the bootstrap css

This reduces the response considerable...

**Comment by maartenbreddels** [comment]
I am not sure #78 is the right solution, but I indeed think we should not inline all the css this way, I'll give it some thought.

**Comment by jf---** [comment]
> I am not sure #78 is the right solution

Agreed, personally I much prefer your #60 approach, closing the PR, leaving the issue open.

**Comment by SylvainCorlay** [comment]
Now that we are loading CSS sepatetely (in master), I think that we can close this specific issue.
