### ISSUE TITLE
Not working with ipysheet

### ISSUE THREAD

**Issue by timkpaine** [QuantStack/voila#87]
Missing `handsontable.js`, it looks for it in `/voila/handsontable.js`.

**Comment by timkpaine** [comment]
Should requests for static assets that hit /voila be redirected to /static? This way you can put those assets in a separate static folder and add it to the static paths. Alternatively, I have a workaround that adds a second static file handler as the last handler to catch any non-matches, which also works.

**Comment by maartenbreddels** [comment]
This was an issue in ipysheet, fixed in https://github.com/QuantStack/ipysheet/pull/91 and released as ipysheet 0.3.2

**Comment by timkpaine** [comment]
Excellent, thanks!

**Comment by jtpio** [comment]
No more missing `handsontable.js` errors, but there still seems to be issues with ipysheet 0.3.2.

Tested using voila master.

Quick Binder demo: https://mybinder.org/v2/gist/jtpio/6016a5a2e0a184aaa11543e3a9da292f/master?urlpath=voila%2Ftree

**Comment by maartenbreddels** [comment]
This was a really tricky issue, #97 should solve it. I actually don't understand why it ever worked, or I must have misremembered it working. I tried to track it by trying old commits, but I think it could never have worked (maybe an older version of ipysheet though).

**Comment by jtpio** [comment]
Thanks @maartenbreddels for the fix.

I triggered a new Binder build and it looks like it's working perfectly now!
