### ISSUE TITLE
Not showing jupyter-matplotlib figure

### ISSUE THREAD

**Issue by davidbrochart** [QuantStack/voila#90]
The following code shows an initial jupyter-matplotlib figure, and then closes it and shows another one when the Refresh button is pressed. It works fine in the notebook, but with voila only the first figure is shown, not the subsequent ones.

```python
%matplotlib widget

import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description='Refresh')
display(button)
def get_fig():
    fig, ax = plt.subplots(1)
    ax.plot(np.arange(10), np.random.random(10))
    return fig
fig = get_fig()

def on_button_clicked(b):
    global fig
    fig.canvas.close()
    fig = get_fig()
button.on_click(on_button_clicked)
```

**Comment by marcocaggioni** [comment]
I was experimenting with a similar problem and I found out as you probably did that %matplolib widget works better than inline to have voila showing the plots but I'm not sure if it is the suggested strategy.

In your case I don't think it is a voila problem I would just clear the ax instead of closing the canvas.
This works for me in voila.

```python
%matplotlib widget

import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description='Refresh')
display(button)

fig, ax = plt.subplots(1)

def get_fig():
    ax.plot(np.arange(10), np.random.random(10))
    return fig

fig = get_fig()

def on_button_clicked(b):
    plt.cla()
    fig = get_fig()
    
button.on_click(on_button_clicked)
```

**Comment by davidbrochart** [comment]
Thanks @marcocaggioni, this works fine.

**Comment by marcocaggioni** [comment]
I would just do

```python
%matplotlib widget

import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description='Refresh')
display(button)

fig, ax = plt.subplots(2,1)

def get_fig():
    ax[0].plot(np.arange(10), np.random.random(10))
    ax[1].plot(np.arange(10), np.random.random(10),color='red')

get_fig()

def on_button_clicked(b):
    ax[0].cla()
    ax[1].cla()
    get_fig()
    
button.on_click(on_button_clicked)
```

**Comment by davidbrochart** [comment]
The point is that the figure can  have one or several ax, and you don't know that in advance.

**Comment by marcocaggioni** [comment]
I would try this. I like to define more explicitly the out so you can have multiple function displaying in that output.

```python
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description='Refresh')
out=widgets.Output()
display(widgets.VBox([button,out]))

@out.capture()
def get_fig():
    fig, ax = plt.subplots(2,1);
    ax[0].plot(np.arange(10), np.random.random(10))
    ax[1].plot(np.arange(10), np.random.random(10),color='red')
    display(fig)
    plt.close(fig)
    

get_fig()

def on_button_clicked(b):
    out.clear_output()
    get_fig()
    
    
button.on_click(on_button_clicked)
```

**Comment by davidbrochart** [comment]
The behavior is different in the notebook and in voila. In voila you have initially 2 plots, and once you refresh you have 4 plots.

**Comment by marcocaggioni** [comment]
Not sure, it works for me, did you remove %matplotlib widget?

**Comment by davidbrochart** [comment]
Actually, latest voila is not even showing the Refresh button anymore.

**Comment by Sedom9** [comment]
Hello!

I did thread, where plot updated every 1 second. In Jupyter all right. But in voila, I haven’t updated plot.

Code below:

def learning_curves(stop_button):

        metrics_graphic_buffer.append(f_score[0])
        metrics_graphic_buffer1.append(f_score[1])
        metrics_graphic_buffer2.append(f_score[2])

        stop_button.on_click(stoping)
        
        with output_learning_curves:
            clear_output()
    #             print("Metrics graphic buffer", metrics_graphic_buffer)
            plt.figure(figsize=(12, 12))
            plt.axis([0, 20, 0, 1.1])
            plt.plot(metrics_graphic_buffer, 'r--', label = 'Tap', 
                     linewidth = 1.0)
            plt.plot(metrics_graphic_buffer1, 'g--', label = 'Toilet', 
                     linewidth = 3.0)
            plt.plot(metrics_graphic_buffer2, 'y--', label = 'Shower', 
                     linewidth = 5.0)
            plt.plot(avr, 'black', label = 'Average f-score', 
                     linewidth = 4.0)
            plt.legend(loc='upper right', prop={'size': 12})
            plt.draw()
            time.sleep(1)

        if flag == False:
            print ('Status flag1', flag)
            break
Initial thread :
thread = threading.Thread(target=learning_curves, args=(stop_button, ))

Start thread :

def on_clicked_Learn_button(state):
    with output_learning_curves:
        thread.start()

Thanx for your help !
