### ISSUE TITLE
How to specify own port number?

### ISSUE THREAD

**Issue by pllim** [QuantStack/voila#99]
What is the option to specify user-defined port number?

**Comment by maartenbreddels** [comment]
Hi,

$`voila --port=7777` would work for example, `$ voila --help` gives you the help for this.

**Comment by giswqs** [comment]
I am trying to deploy voila on the Goolge cloud platform. The default voila port 8866 works fine, but when I try to specify the port as 80, I got the following error. Any suggestions? Thanks. 

```
voila --port=80 --no-browser --strip_sources=True --enable_nbextensions=True notebooks/
```

![](https://i.imgur.com/fw6MpKq.png)
